name: Build check on PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'TailwindTraders.Website/**'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install build dependencies for node-sass
      run: |
        sudo apt-get update
        sudo apt-get install -y python-is-python2 g++ make

    - name: Install dependencies in client app
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release
        dotnet publish -c Release -o publish
